print ("1. True and True = %s" % str(True and True))
print ("2. Flase and True = %s" % str(False and True))
print ("3. 1==1 and 2==1 = %s" % str((1 == 1) and (2 == 1)))
print ("4. 'test' == 'test' = %s" % str('test' == 'test'))
print ("5. 1==1 or 2!=1 = %s" % str(1==1 or 2!=1))
print ("6. True and 1==1 = %s" % str(True and 1==1))
print ("7. False and 0!=0 = %s" % str(False and (0!=0)))
print ("8. True or 1==1 = %s" % str(True or (1==1)))
print ("9. 'test' == 'testing' = %s" % str('test' == 'testing'))
print ("10. 1!=0 and 2==1 = %s" % str((1!=0) and (2==1)))
print ("11. 'test'!='testing' = %s" % str('test'!='testing'))
print ("12. 'test'== 1 = %s" % str('test'== 1))
print ("13. not(True and False) = %s" % str(not(True and False)))
print ("14. not(1==1 and 0!=1) = %s" % str(not(1==1 and 0!=1)))
print ("15. not(10==1 or 1000==1000) = %s" % str(not((10==1) or (1000==1000))))
print ("16. not(1!=10 or 3==4) = %s" % str(not((1!=10) or (3==4))))
print ("17. not('testing'=='testing' and 'Zed' == 'CoolGuy') = %s" % str(not('testing'=='testing' and 'Zed' == 'CoolGuy')))
print ("18. 1==1 and not('testing'==1 or 1==0) = %s" % str((1==1) and not(('testing'==1) or (1==0))))
print ("19. 'chunky' == 'bacon' and not(3==4 or 3==3) = %s" % str('chunky' == 'bacon' and not((3==4) or (3==3))))
print ("20. 3==3 and not('testing'=='testing' or 'Python'=='Fun') = %s" % str((3==3) and not('testing'=='testing' or 'Python'=='Fun')))

print("extra 1. 'test' and 'test' = = %s" % str('test' and 'test'))
print("extra 2. 1 and 1 = = %s" % str(1 and 1))
print("extra 3. False and 1 = = %s" % str(False and 1))
print("extra 4. True and 1 = = %s" % str(True and 1))